### ISSUE TITLE
I got this Issue

### ISSUE THREAD

**Issue by Felitendo** [qjcXu/Flow.Launcher.Translation#3]
Please open new issue in: https://github.com/qjcXu/Flow.Launcher.Translation/issues/new
1. upload log file: C:\Users\Feli2\AppData\Roaming\FlowLauncher\Logs\1.9.5\2022-10-03.txt
2. copy below exception message

Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 10.0.22623.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 10/03/2022 19:47:35
Exception:
Translate Tool Exception: 
Websites: https://github.com/qjcXu/Flow.Launcher.Translation
Author: qjc
Version: 0.1.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Translate Tool|node:internal/modules/cjs/loader:958
  throw err;
  ^

Error: Cannot find module 'C:\Users\Feli2\AppData\Roaming\FlowLauncher\Plugins\Translate'
    at Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
    at Module._load (node:internal/modules/cjs/loader:803:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.9.1

 ---> System.IO.InvalidDataException: Translate Tool|node:internal/modules/cjs/loader:958
  throw err;
  ^

Error: Cannot find module 'C:\Users\Feli2\AppData\Roaming\FlowLauncher\Plugins\Translate'
    at Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
    at Module._load (node:internal/modules/cjs/loader:803:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.9.1

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 288
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 302
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 322
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 616
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 590
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lukxu** [comment]
> Please open new issue in: https://github.com/qjcXu/Flow.Launcher.Translation/issues/new
> 
> 1. upload log file: C:\Users\Feli2\AppData\Roaming\FlowLauncher\Logs\1.9.5\2022-10-03.txt
> 2. copy below exception message
> 
> Flow Launcher version: 1.9.5 OS Version: Microsoft Windows NT 10.0.22623.0 IntPtr Length: 8 x64: True
> 
> Python Path: Date: 10/03/2022 19:47:35 Exception: Translate Tool Exception: Websites: https://github.com/qjcXu/Flow.Launcher.Translation Author: qjc Version: 0.1.1 Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Translate Tool|node:internal/modules/cjs/loader:958 throw err; ^
> 
> Error: Cannot find module 'C:\Users\Feli2\AppData\Roaming\FlowLauncher\Plugins\Translate' at Module._resolveFilename (node:internal/modules/cjs/loader:955:15) at Module._load (node:internal/modules/cjs/loader:803:27) at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) at node:internal/main/run_main_module:18:47 { code: 'MODULE_NOT_FOUND', requireStack: [] }
> 
> Node.js v18.9.1
> 
> ---> System.IO.InvalidDataException: Translate Tool|node:internal/modules/cjs/loader:958 throw err; ^
> 
> Error: Cannot find module 'C:\Users\Feli2\AppData\Roaming\FlowLauncher\Plugins\Translate' at Module._resolveFilename (node:internal/modules/cjs/loader:955:15) at Module._load (node:internal/modules/cjs/loader:803:27) at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) at node:internal/main/run_main_module:18:47 { code: 'MODULE_NOT_FOUND', requireStack: [] }
> 
> Node.js v18.9.1
> 
> at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 288 at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 302 at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 322 at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191 --- End of stack trace from previous location --- at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34 at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190 --- End of inner exception stack trace --- at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210 at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 616 --- End of stack trace from previous location --- at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 590 at System.Threading.Tasks.Task.<>c.b__140_0(Object state) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

![image](https://user-images.githubusercontent.com/80330629/195985370-e7f1ab3a-bb65-4d18-b87e-0bd4dbdc002c.png)

Sorry, You can try to reinstall this plugin

**Comment by lukxu** [comment]
Sorry, i got this bug.
So i fixed this bug in my lastest release.
