### ISSUE TITLE
安装后无法使用 "Translation Tool: Failed to respond"

### ISSUE THREAD

**Issue by Ardenet** [qjcXu/Flow.Launcher.Translation#9]
# Description

用 `tr` 激活出现下图的情况, 不管是设置 appid/key 还是查询都无法正常使用
![image](https://github.com/qjcXu/Flow.Launcher.Translation/assets/69284622/3459d578-c8f2-441c-84cc-af3f1e390967)
简单看了下 flow 的插件开发指南和源码, 可能是 flow 这边的 jsonRPC 过程出现了问题, 但不清楚具体是啥, 而且其它插件都正常运行, 下面的报错显示`索引越界`

# Error Log

```
Flow Launcher version: 1.17.1
OS Version: 19045.3996
IntPtr Length: 8
x64: True

Python Path: C:\Program Files\Python312\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 02/07/2024 19:49:51
Exception:
Translation Tool Exception: 
Websites: https://github.com/qjcXu/Flow.Launcher.Translation
Author: qjc
Version: 1.3.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Flow.Launcher.Core.Plugin.NodePlugin.RequestAsync(JsonRPCRequestModel request, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\NodePlugin.cs:line 31
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 264
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 230
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 294
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by lukxu** [comment]
@FloatStream 1.17.1版本改了JSONRPC的格式，我重新改下吧

**Comment by Ardenet** [comment]
ok, 感谢大佬

**Comment by Ardenet** [comment]
@qjcXu 更新1.17.2后插件可以正常使用了, 就是它那边处理可能出了些问题

[1.17.2 Release Note](https://github.com/Flow-Launcher/Flow.Launcher/releases/tag/v1.17.2)

**Comment by lukxu** [comment]
@FloatStream Flow Launcher的 issue #2553有个大佬已经解决了这个问题

**Comment by Ardenet** [comment]
ok, 我把这个issue关了
